### ISSUE TITLE
_consume_request implementation is vulnerable to denial of service attacks

### ISSUE THREAD

**Issue by twosigmajab** [deshaw/wsgi-kerberos#11]
The current `_consume_request` implementation reads the `Content-Length` header and blindly tries to `read` and buffer that many bytes into memory without regard for size:
https://github.com/mkomitee/wsgi-kerberos/blob/c2199a3c1143c0a340b576c0d547442224080e53/wsgi_kerberos.py#L57

I think it would be safer to only read up to `read_max` bytes.

**Comment by hawicz** [comment]
It makes sense to have some kind of limit.  Where are CHUNK_SIZE and MAX_REQUEST_SIZE coming from?

**Comment by twosigmajab** [comment]
@mkomitee Glad that makes sense to you. Those would be new constants that this library should define. Any favorite values?

**Comment by mkomitee** [comment]
That wasn’t me that was responding to you.

We read (and discard) all the data because it’s a requirement of the protocol, but we could read it in smaller chunks so we don’t consume all of the memory on the system.

**Comment by twosigmajab** [comment]
Cool, so sounds like you'd accept a PR to read it in smaller chunks. I'll submit one if no one beats me to it.

**Comment by twosigmajab** [comment]
Please see #15.
