### ISSUE TITLE
_consume_request does not handle Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by twosigmajab** [deshaw/wsgi-kerberos#12]
The current implementation of `_consume_request` assumes a 0-length body when a `Content-Length` header is not sent:
https://github.com/mkomitee/wsgi-kerberos/blob/c2199a3c1143c0a340b576c0d547442224080e53/wsgi_kerberos.py#L49

However, clients may stream request bodies using the `Transfer-Encoding: chunked` without sending a `Content-Length` header.

To handle this, we would just read chunks of data from the socket until hitting`\r\n\r\n`.

Maybe we're fine not handling this, and just giving clients "Broken Pipe" for such requests? If that's the case, the code change here could just be to update the comments around this code to document that decision.

**Comment by twosigmajab** [comment]
Probably worth addressing at the same time as #11.

**Comment by mkomitee** [comment]
Good point. Do we know what web servers do when it comes to chunked transfer encoding from the client?

**Comment by twosigmajab** [comment]
Sorry @mkomitee, not sure what you're asking. Can you be more specific than "what web servers do"? (I'd say "they read chunks of data from the socket until hitting `\r\n\r\n`", but I already said that.) Here's an example of gunicorn's `ChunkedReader`, in case it's helpful:

https://github.com/benoitc/gunicorn/blob/19.9.0/gunicorn/http/body.py#L11

You can see this used (e.g. in the `Body.read*()` methods, such as [here](https://github.com/benoitc/gunicorn/blob/19.9.0/gunicorn/http/body.py#L212)) to read (1024-byte) chunks at a time [until hitting a `\r\n\r\n`](https://github.com/benoitc/gunicorn/blob/19.9.0/gunicorn/http/body.py#L47).

**Comment by twosigmajab** [comment]
A complication: the WSGI standard itself doesn't permit chunked transfer encoding, but several WSGI servers (e.g. uWSGI, gunicorn, mod_wsgi) support it via `environ["wsgi.input_terminated"] = True`.

Ref:
* benoitc/gunicorn#1653
* unbit/uwsgi#1428
* https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIChunkedRequest.html
