### ISSUE TITLE
Drop support for Python < 3.6

### ISSUE THREAD

**Issue by twosigmajab** [deshaw/wsgi-kerberos#22]
Python 3.6 is the oldest version of Python that is not past end-of-life.

Ref: https://www.python.org/downloads/

This would reduce the maintenance burden for WSGI-Kerberos (e.g. less Python versions in the CI matrix that would be needed for #21), would enable dropping the test dependency on `mock`, and would enable dropping e.g. string/bytes compatibility code that imposes maintenance and performance costs.

**Comment by propertone** [comment]
That sounds fine to me. We should keep 2.7 support for now though - although it's EOL, it's still widely used in enterprise.

**Comment by propertone** [comment]
Sorry, I misunderstood the request. I'd like to keep python 2.7 support for now, at least until the next few releases that will include the recently merged PRs, and any related bug fixes. We can re-evaluate this again in half a year or so, or whenever there is a new py3 only compelling feature.
