### ISSUE TITLE
Add support for auth_succeeded_callback

### ISSUE THREAD

**Issue by twosigmajab** [deshaw/wsgi-kerberos#23]
Would you accept a PR that adds support for an optional `auth_succeeded_callback` argument? If supplied, WSGI-Kerberos would call the callback upon successful authentication, passing in the authenticated user.

This would enable users to pass something like `auth_succeeded_callback=lamdba user: structlog.contextvars.bind_contextvars(user=user)`, to enable all subsequent log calls made during the lifetime of the request to automatically include the authenticated user, which can be really convenient.

We are already doing this in our fork of WSGI-Kerberos, and would love to get it upstreamed.

Thanks for your consideration!

Ref: https://www.structlog.org/en/stable/contextvars.html

**Comment by propertone** [comment]
That might be useful. Few questions:
* Is there a reason you can't do that with wsgi middleware instead?
* Would it be better to pass `environ` instead of (or in addition to) `user`, in case the callback wants to make use of other variables from the wsgi environment?

**Comment by twosigmajab** [comment]
Thanks for the good questions! I originally thought that doing this in separate WSGI middleware instead would be less convenient for our use case, but some refactoring created a perfect place for this to go in our own middleware so that no changes to WSGI-Kerberos are required. Closing this as no longer needed. Thanks again!
