### ISSUE TITLE
Remove use of self.service in calls to authGSSServerInit

### ISSUE THREAD

**Issue by hawicz** [deshaw/wsgi-kerberos#3]
When a client uses Kerberos to authenticate to a server it presents a token for a specific service name.  The server then checks its keytab to see if it has a key for that name, and if it does then the authentication can successfully complete.  The server does not need to know ahead of time what name a client might use.

Pre-specifying a service when calling authGSSServerInit needlessly constrains what service names can work and breaks any clients that attempt to access the service by another name, even if a key for that service name exists in the keytab.

The simplest solution is to simply pass the empty string ("") to [authGSSServerInit()](https://github.com/mkomitee/wsgi-kerberos/blob/master/wsgi_kerberos.py#L140), and drop use of hostname and self.service entirely.

Also:
Attempting to get the server principal details from the keytab using a provided hostname (as is done in __init__) may have some value as a sanity check, but:
1) It should be clearly characterized as just an optional sanity check, and not actually required for proper operation of the service.
2) To be maximally useful, it needs to take a list of service names, since services can have multiple keys.
3) Just because a particular set of service names are or are not valid when the service starts doesn't mean that will be the case when an actual authentication is attempted.  Keys can be added to (or removed from) a keytab without restarting the service.

It may be easier to simply remove that code.

**Comment by mkomitee** [comment]
Agreed on all counts.

**Comment by hawicz** [comment]
Great!  I believe my colleague @twosigmajab is working on some fixes, so there should be a pull request to go along with this at some point.

**Comment by twosigmajab** [comment]
Submitted as #5. Thanks!
