### ISSUE TITLE
Only supports arcfour-hmac keytab enctypes?

### ISSUE THREAD

**Issue by dude-zero** [deshaw/wsgi-kerberos#32]
It seems the library only supports rc4-hmac, at least according to the output when running example_application.py:
1.1.2.2 - - [02/Oct/2021 10:40:32] "GET / HTTP/1.1" 403 9
ERROR:wsgi_kerberos:Unhandled GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Request ticket server HTTP/HOSTNAME.FQDN@REALM kvno 1 found in keytab but not with enctype rc4-hmac', 100002))

Can this code support aes256-cts-hmac-sha1-96 or aes128-cts-hmac-sha1-96 keytab enctypes?

In addition it seems that lowercase http/service_principal keytab entries are ignored, in order to be recognized they must be HTTP/service_principal@REALM.  I don't recall this being a requirement previously.

**Comment by propertone** [comment]
This is likely an issue in your Kerberos configuration. The errors you see from wsgi_kerberos example application are coming from the Kerberos libraries themselves, not wsgi_kerberos.
