### ISSUE TITLE
unhandled kerberos.KrbError

### ISSUE THREAD

**Issue by twosigmajab** [deshaw/wsgi-kerberos#7]
https://github.com/mkomitee/wsgi-kerberos/blob/c2199a3c1143c0a340b576c0d547442224080e53/wsgi_kerberos.py#L153

calls `authGSSServerStep(state, client_token)` even when a `client_token` of empty string is provided.

In this case, a `kerberos.KrbError` is produced that is propagated, instead of being swallowed by the
```python
except kerberos.GSSError:
    pass
```
[`GSSError` is a subclass of `KrbError`](https://github.com/apple/ccs-pykerberos/blob/133299a9446a78b07eb7b337269507972f6e12ef/pysrc/kerberos.py#L33), so the `except` statement is too narrow to catch the `KrbError` that is raised in this case.

Google Chrome triggers this when a WSGI-Kerberos-wrapped server sends two 401 responses in a row (the first sent by WSGI-Kerberos, the second by the wrapped WSGI app). In this case, Chrome sends an Authorization header with a client token of empty string, triggering the unhandled KrbError, ultimately resulting in 500 internal server error.

Should WSGI-Kerberos have special handling of the invalid `client_token == ""` case without passing it through to `authGSSServerStep`, and/or broaden the `except` statement to swallow `KrbError`? Testing with only the latter change results in sending a 403 response.

**Comment by twosigmajab** [comment]
@mkomitee @hawicz, what do you think?

**Comment by hawicz** [comment]
I'd say broaden the except, but don't explicitly check for an empty token, at least not inside the _authenticate() method.  If you want to include that in the calling code, which already has a case for no authorization header at all, then sure, but with the wider exception it's not really needed.

**Comment by twosigmajab** [comment]
Submitted #8 with a fix for this.

/cc @mkomitee, in case you have time to review that (and ideally my other outstanding PRs, #5 and #6), and do a new release with the fixes. Thanks!
